apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
      command: ["sleep", "1000000"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "128m"
        limits:
          memory: "64Mi"
          cpu: "256m"
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data-pvc
