---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 30%
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      volumes:
        - name: app
          emptyDir: {}
      containers:
        - name: web
          image: sviklim/kubernetes-intro-web
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /index.html
              port: "8080"
          livenessProbe:
              tcpSocket: { port: "8000" }
          volumeMounts:
            - name: app
              mountPath: /app
          resources:
            requests:
              memory: "32Mi"
              cpu: "128m"
            limits:
              memory: "64Mi"
              cpu: "256m"
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
          volumeMounts:
            - name: app
              mountPath: /app
