kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "feature- gates": "VolumePVCDataSource=true"
    scheduler:
      extraArgs:
        "feature- gates": "VolumePVCDataSource=true"
    controllerManager:
      extraArgs:
        "feature- gates": "VolumePVCDataSource=true"
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    metadata:
      name: config
    nodeRegistration:
      kubeletExtraArgs:
        "feature- gates": "VolumePVCDataSource=true"
