---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol-role-binding
subjects:
- kind: ServiceAccount
  name: carol
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: carol
  apiGroup: rbac.authorization.k8s.io
