apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: value
spec:
  volumes:
    - name: app
      emptyDir: {}
  containers:
    - name: web
      image: sviklim/kubernetes-intro-web
      imagePullPolicy: Always
      volumeMounts:
        - name: app
          mountPath: /app
      resources:
        requests:
          memory: "32Mi"
          cpu: "128m"
        limits:
          memory: "64Mi"
          cpu: "256m"
  initContainers:
    - name: init
      image: busybox
      command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
      volumeMounts:
        - name: app
          mountPath: /app
